config/routes.rb
Rails.application.routes.draw do

  get  'payment_accounts/view' => 'payment_account#view'
  get  'payment_accounts' => 'payment_account#new'

  post   'payment_accounts' => 'payment_account#create'
  delete 'payment_accounts/:id' => 'payment_account#delete', as: :payment_account
  delete 'payment_accounts' => 'payment_account#delete_all'

  post 'payment_accounts/:id/op' => 'payment_account#money_op', as: :payment_account_op

  devise_for :users
  post 'api/users.json', to: 'api/registrations#create', defaults: { format: 'json' }
  root to: 'home#index'

end

app/models/payment_account.rb
# == Schema Information
#
# Table name: payment_accounts
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  current_balance :decimal(, )
#  created_at      :datetime
#  updated_at      :datetime
#  name            :string(255)
#

class PaymentAccount < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payment_account

  validates_format_of :email, with: /\A([^@\s]+)@([^@\s]+)\.edu\z/, message: " must be a .edu email"
  
  def payment_accounts
    self.payment_account
  end
end

app/controllers/Api/registrations_controller.rb
class Api::RegistrationsController  < ApplicationController

  skip_before_filter :verify_authenticity_token
  respond_to :json

  def create

    user = User.new(user_params)
    if user.save
      render :json => user.as_json(:auth_token=>user.authentication_token, :email=>user.email), :status=>201
      return
    else
      warden.custom_failure!
      render :json => user.errors, :status=>422
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payment_account_controller.rb
class PaymentAccountController < ApplicationController
  before_action :authenticate_user!

  def view
    @accounts = current_user.payment_accounts
    render "view"
  end

  def money_op
    @account = current_user.payment_accounts.find(params[:id])
    if params[:op] == "credit"
      @account.current_balance += params[:ammount].to_f
    elsif params[:op] == "debit"
      @account.current_balance -= params[:ammount].to_f
    end
    @account.save
    redirect_to_view and return
  end

  def new
    @account = current_user.payment_account.new
    render "new"
  end

  def create
    @account = current_user.payment_account.create(account_params)
    if @account != nil
      # Go back to the account view
      redirect_to_view and return
    else
      @error_message = "There was a problem creating your account"
      render "new"
    end
  end

  def delete
    current_user.payment_accounts.find(params[:id]).delete
    redirect_to_view and return
  end

  def delete_all
    current_user.payment_accounts.each {|a| a.delete }

    # Go back to the account view
    redirect_to_view and return
  end


  protected ####################################################################

  def redirect_to_view
    redirect_to payment_accounts_view_path
  end

  def account_params
    params.require(:payment_account).permit(:name)
      .merge({user_id: current_user.id, current_balance: 0})
  end

  def credit_params
    
  end

  def debit_params

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payment_account_helper.rb
module PaymentAccountHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EveryoneRichBank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    @media only screen and (min-width:768px) and (max-width:991px) {
      .navbar-nav {
        font-size: 0.9em;
      }
    }
  </style>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">[ER]Bank</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="/#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="/#about">About Us</a>
                  </li>
                <% if user_signed_in? %>
                  <li class="page-scroll">
                    <%= link_to "Payment Accounts", payment_accounts_view_path %>
                  </li>
                <% end %>
                <li class="page-scroll">
                  <%= render 'devise/menu/registration_items' %>
                </li>
                <li class="page-scroll">
                    <%= render 'devise/menu/login_items' %>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<div class="content-container">

    <%= yield %>
</div>

</body>
</html>

app/views/payment_account/new.html.erb
<div class="container">
  <h4>Create new payment account</h4>
  <div class="well">
    <%= form_for @account do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/payment_account/view.html.erb
<style>
  .em-panel-actions {
    margin: 0
  }

</style>

<div class="container">
  <h4>Accounts:</h4>
  <div class="well">
    <div class="clearfix container-fluid">
    <% if @accounts.size != 0 %>
      <% @accounts.each do |account| %>
        <div class="item col-xs-12 col-md-6 col-lg-6">
          <div class="panel panel-success">
            <div class="panel-heading">
              <%= account.name %>
            </div>
            <div class="panel-body">
              <strong>Balance:</strong>
              <%= account.current_balance %>
            </div>
            <div class="em-panel-footer panel-footer clearfix">
              <ul class="em-panel-actions list-inline pull-right">
                <li>
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal<%= account.id %>" >
                    Debit/Credit
                  </button>
                </li>
                <li>
                  <%= form_tag(payment_account_path(account), method: 'delete', class: 'form-inline', role: 'form') do %>
                    <%= submit_tag("Delete", class: 'btn btn-danger') %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
      </div>
      <%= link_to "Create new account...", payment_accounts_path %>
    <% else %>
      <p>You do not have any accounts</p>

      <%= link_to "Create new account...", payment_accounts_path %>
    <% end %>
  </div>

  <% if @accounts.size != 0 %>
    <div class="panel panel-danger">
      <div class="panel-heading">DANGER ZONE</div>
      <div class="panel-body">
        <%= form_tag(payment_accounts_path, method: 'delete', role: 'form') do %>
          <%= submit_tag("Delete All", class: 'btn btn-danger') %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% @accounts.each do |account| %>
  <div class="modal fade" id="myModal<%= account.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Account: <%= account.name %></h4>
        </div>
        <%= form_tag(payment_account_op_path(account), method: 'post', role: 'form') do %>
          <div class="modal-body">
            <div class="form-group">
              <%= label_tag :op, 'Operation', class: 'control-label'%>
              <%= select_tag :op, options_for_select([ :debit, :credit], :debit), class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= label_tag :ammount, 'Ammount', class: 'control-label'%>
              <%= number_field_tag :ammount, nil, class: 'form-control', placeholder: "1.0" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag("Submit", class: 'btn btn-success') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>